### ISSUE TITLE
Known Bugs

### ISSUE THREAD

**Issue by WamWooWam** [UnicordDev/Unicord#15]
**NOTE:** These are not in priority order in any way, nor is this an exhaustive list.

- [x] Discord WebSocket deadlock (#7)
- [x] Selection of channels and servers can be buggy
- [x] Crash when opening new windows on certain versions of Windows 10
- [x] Context Flyouts occasionally just die
- [ ] The video trimmer doesn't hide it's transport controls while playing
- [x] Contact syncing doesn't work
- [x] The themes list doesn't refresh properly once a new theme is added
- [x] Profile overlay breaks `CompactOverlay`
- [x] Message copying is broken

**Comment by Redblueflame** [comment]
Got the crash while opening new window.
The error:
Windows.UI.Xaml.Markup.XamlParseException
  HResult=0x802B000A
  Message=The text associated with this error code could not be found.

Cannot find a Resource with the Name/Key ControlCornerRadius [Line: 325 Position: 64]
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

I'm in Windows 10 Enterprise Insider Preview Build 18932.rs_prerelease.190628-1650

**Comment by WamWooWam** [comment]
> Got the crash while opening new window.
> The error:
> Windows.UI.Xaml.Markup.XamlParseException
> HResult=0x802B000A
> Message=The text associated with this error code could not be found.
> 
> Cannot find a Resource with the Name/Key ControlCornerRadius [Line: 325 Position: 64]
> Source=
> StackTrace:
> I'm in Windows 10 Enterprise Insider Preview Build 18932.rs_prerelease.190628-1650

This has actually been fixed! I forgot to mention like a dummy

**Comment by bgiesing** [comment]
Popping out a DM into an overlay window shows the login screen then crashes 
![image](https://user-images.githubusercontent.com/7895463/68599743-bcdd0c80-0466-11ea-99c0-b6e24f420c75.png)

**Comment by WamWooWam** [comment]
Can I ask you to spin this off into its own issue @bgiesing? I've a few questions I need to ask
