### ISSUE TITLE
Sent messages are RTL and it mirrors the profile picture

### ISSUE THREAD

**Issue by Vas0sky** [UnicordDev/Unicord#48]
I don't know how good of an idea is to use RTL to display your messages, winUI's implementation is a bit buggy, I suggest displaying them normally like discord does.

Pic shown on the server
![image](https://user-images.githubusercontent.com/13967613/92322882-657edd00-f034-11ea-9826-a4ed51fd8e41.png)

My actual pic
![image](https://user-images.githubusercontent.com/13967613/92322890-79c2da00-f034-11ea-8bb5-caa65858b92c.png)

**Comment by WamWooWam** [comment]
I didn't actually notice this, as threaded messages like this are a work in progress optional feature and probably won't end up "shipping" in the form they are currently.
