### ISSUE TITLE
Why Unicord launches in portrait mode?

### ISSUE THREAD

**Issue by xperiandri** [UnicordDev/Unicord#61]
![image](https://user-images.githubusercontent.com/2365592/102530961-5505e600-40aa-11eb-98b7-0710b5c6d811.png)

The screen at the bottom must be in landscape mode. But it switches to portrait and back causing a huge lag.

**Comment by WamWooWam** [comment]
Uhhh, that's a very good question. I wonder if it's related to the manifest file? I'll have to check

**Comment by xperiandri** [comment]
I suppose so, the must be a primary mode.

**Comment by WamWooWam** [comment]
Also fixed this in v1.8.1-beta and also v2.0.0-alpha.1 :)
