### ISSUE TITLE
Duplicate speakers and microphones in Input and Output Device list

### ISSUE THREAD

**Issue by prakharb5** [UnicordDev/Unicord#69]
(nice issue number, XD)
![image](https://user-images.githubusercontent.com/51435948/109343735-cd034000-7893-11eb-80f9-8f789d1ee979.png)

and

![image](https://user-images.githubusercontent.com/51435948/109343771-d7bdd500-7893-11eb-9972-abfbe03b5bc5.png)

**Comment by WamWooWam** [comment]
Unicord shows whatever devices are available according to Windows, so this doesn't appear to be an bug *in* Unicord itself
