### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by TeamSHEILD** [UnicordDev/Unicord#73]
on my windows phone running windows phone 10 i am unable to install the app. I cant find a tutorial online to find if im doing it right but when i run the appx bundle it asks if i want to install it but when i select yes it doesnt do anythoing

**Comment by cefre00** [comment]
There are 2 ways to install an appxbundle from github, let me share with you this link, which is showing the easier one, especially on a slower device like the Lumia 650: http://allaboutwindowsphone.com/features/item/23922_Installing_Strix_Music_on_your.php

Don't follow Steve's tutorial, but go to Arlo's page and click in "Install" and there will be a 2 line installation instruction for WIndows Phone using the Device Portal functionality. That will work fine... Make sure you have dependencies installed!

**Comment by WamWooWam** [comment]
This is not an issue with Unicord, if you need support installing it, please join the Discord server and ask there.
