### ISSUE TITLE
Bug: does not work on Win11

### ISSUE THREAD

**Issue by VMGuy23** [UnicordDev/Unicord#76]
Login page is stuck loading forever, reload goes to about:blank

How do I do token?

**Comment by Jimmy-Blue** [comment]
What is your problem? Can I see the screen?

**Comment by VMGuy23** [comment]
Wh is invald

**Comment by WamWooWam** [comment]
it works fine on windows 11, these are not windows 11 specific issues.
for bugs, please open individual issues with actual detail (see the templates)
for support requests, please see the discord
