### ISSUE TITLE
Opening a new window for a server does not work

### ISSUE THREAD

**Issue by xperiandri** [UnicordDev/Unicord#82]
![image](https://user-images.githubusercontent.com/2365592/143773996-6e25618a-698d-4634-8bb8-97824f652f98.png)

**Comment by xperiandri** [comment]
Fixed?

**Comment by WamWooWam** [comment]
i think i mentioned this but if not, this isn't a bug report, it's a screenshot, please file actual actionable feedback

**Comment by xperiandri** [comment]
Do you mean that when you invoke a context menu on any server and choose `Open in a new Window` menu item, then the new Windows opens?

**Comment by WamWooWam** [comment]
i mean file a proper bug report lol
