### ISSUE TITLE
Opening a new Window for a server does not work 

### ISSUE THREAD

**Issue by xperiandri** [UnicordDev/Unicord#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Executing `Open in a new Window` menu item from the server context menu does nothing

### Expected Behavior

New Window for that server opens

### Steps To Reproduce

1. Invoke a context menu on any server icon on the left sidebar
2. Select `Open in a new Window` menu item
3. No new Windows opens

### Screenshots

![image](https://user-images.githubusercontent.com/2365592/143773996-6e25618a-698d-4634-8bb8-97824f652f98.png)

### Version

1.7.6

### Windows Version

Windows 11 (22000)

### Platform?

Desktop

**Comment by xperiandri** [comment]
😉

**Comment by WamWooWam** [comment]
That button was vestige of former plans that never came to fruition, and would require significant rearchitecting to do today, sorry!
