### ISSUE TITLE
I can't build the project correctly

### ISSUE THREAD

**Issue by LudovicBouvierJohnston** [UnicordDev/Unicord#86]
For some reason I can't build the project correctly. There is some dependencies that Visual Studio can't see see for some reason. Here is a screenshot of what I have. The rebuild always fail and I made sure to install abseil correctly

Thanks in advance 😊

![image](https://user-images.githubusercontent.com/65404017/159168884-403c80e2-de72-43c7-902f-bf384a64feb2.png)

**Comment by WamWooWam** [comment]
Currently building the main branch is a futile exercise for most people, I'd recommend building `redesign` or registering for builds through the Microsoft Store for most people

**Comment by LudovicBouvierJohnston** [comment]
Thank you so much I have it now and I can log in correctly. Does Push Notifications supposed to work in the background? I think I am not receiving them because Windows is suspending Unicord? Should I prevent this behaviour in in Battery Usage setting? 

![image](https://user-images.githubusercontent.com/65404017/159170220-a2204008-bed7-4dc4-b8d5-b35675489b45.png)

**Comment by WamWooWam** [comment]
The `redesign` branch currently excludes the background push client from builds, there's some packaging work yet to be done to re-enable that functionality, builds from the store don't have this limitation

**Comment by LudovicBouvierJohnston** [comment]
How do I try the builds from the Store? I can't seem to find it in the Microsoft Store...

**Comment by WamWooWam** [comment]
There's a registration process through the Discord server that adds you to the private flight

**Comment by LudovicBouvierJohnston** [comment]
Great will sign up right now thank you!

**Comment by LudovicBouvierJohnston** [comment]
I have registered on Google Form thank you!

**Comment by WamWooWam** [comment]
Fixed all the issues noted in here :)
