### ISSUE TITLE
Could you please resign the certificate? 

### ISSUE THREAD

**Issue by foxnoodles** [UnicordDev/Unicord#87]
It has expired and there is no easy way to install the app. I know it's outdated but I'd love to try it anyway. If thats not too much of a husle for you

**Comment by hooddy** [comment]
> husle

Just change time in your tab/phone to match cert date.

**Comment by WamWooWam** [comment]
for the record i have looked into this, it's annoyingly not really possible without rebuilding the project through visual studio, which depends on a lot of stuff i dont really have right now

**Comment by BreeceW** [comment]
> for the record i have looked into this, it's annoyingly not really possible without rebuilding the project through visual studio

You can sign the package using signtool.exe, which ships as a part of the Windows SDK

```SignTool sign /fd SHA256 /a /f <Path to Certificate>.pfx <File path>.msix```

**Comment by WamWooWam** [comment]
correct, now do that to an msixbundle where you have to do it to each individual msix, + the bundle itself while also creating the bundle correctly

it's a real hassle

**Comment by foxnoodles** [comment]
We need a bat file to do that  automatically that would be nice

**Comment by RefriZaddo** [comment]
> > husle
> 
> Just change time in your tab/phone to match cert date.

what if someone doesn't wanna? (welp i guess they are just stubborn right)

**Comment by WamWooWam** [comment]
Hi, I fixed this in v1.8.1-beta, go download that release :)
