### ISSUE TITLE
Cannot compille the redesign branch

### ISSUE THREAD

**Issue by dzastsed** [UnicordDev/Unicord#88]
Redesign branch doesnt seem to compile if using x64 target, I get missing assembly reference errors.
![paveikslas](https://github.com/UnicordDev/Unicord/assets/63074962/70dd0bf4-290f-4155-9257-9452df0d842f)
using VS2019 on windows 11 22621

**Comment by WamWooWam** [comment]
oh did i not push that? i'll take a look in a couple

**Comment by dzastsed** [comment]
any update?

**Comment by TheDinoDude** [comment]
> oh did i not push that? i'll take a look in a couple

any updates?

**Comment by WamWooWam** [comment]
Fixed! Should build fine now :)
