### ISSUE TITLE
Invalid certificate

### ISSUE THREAD

**Issue by LumiaWindows** [UnicordDev/Unicord#92]
The other day I wanted to install Unicord on my laptop running Windows 10. It said that the Certificate was invalid. So can you devs fix this?
![image](https://github.com/UnicordDev/Unicord/assets/159555654/3b5b10fa-9e9c-46c7-906c-97e98be9a280)

**Comment by damirap2020** [comment]
The only way to fix is is to rebuild it. For now just set the date back to the time when cert worked (kinda absurd but thats the only solution i know about and that actually worked for me)

**Comment by iProgramMC** [comment]
Just a fact of life. If you want, you can set your time to 2022 (or 2021 after June 28th) during the install and launch, and set it back to 2024 when you actually want to log in. Or wait until Wam rebuilds Unicord. Due to his lack of time though, it's going to be a while.

**Comment by WamWooWam** [comment]
Hi, I fixed this in v1.8.1-beta, go download that release :)
