### ISSUE TITLE
Can't build on linux with mono

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [UnicordDev/Unicord#94]
Unable to build on linux with mono framework.
Tried doing `xbuild Unicord/Unicord.csproj` but it said it needed `xmlns="http://schemas.microsoft.com/developer/msbuild/2003"` in the `<Project>` element.

Added it and it said there's "No target found in the project"

Please fix that or if I'm doing something wrong add precise instructions for building the project from command line in README

**Comment by WamWooWam** [comment]
You cannot build this project on Linux, you sure as shit can't build this project with Mono. Sorry.

**Comment by TanyaEleventhGoddess** [comment]
> You cannot build this project on Linux, you sure as shit can't build this project with Mono. Sorry.

Why? Isn't an opensource project supposed to be cross-platform? We have an opensource C# compiler already
